<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{f48db1e3-9dde-48d5-bccc-d0cb3279a1dc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	//Voor Motion
	fbReadXaxisStatus: MC_ReadStatus;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[RunTCP(); //Runs TCP server, lights etc are controlled with this
   peddal();

fbReadXaxisStatus(
	Axis:=GVL_NC.stXAxis , 
	Enable:= GVL_AxisCtr.bXAxisEnable , 
	Valid=> , Busy=> , Error=> , 
	ErrorID=> , ErrorStop=> , 
	Disabled=> , Stopping=> , 
	StandStill=> , DiscreteMotion=> , 
	ContinuousMotion=> , SynchronizedMotion=> , 
	Homing=> , ConstantVelocity=> , 
	Accelerating=> , Decelerating=> , 
	Status=> GVL_NC.stXaxisStatus);
	POUNCPowerOn();
	movements();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="91" Count="0" />
      <LineId Id="149" Count="0" />
      <LineId Id="38" Count="3" />
      <LineId Id="44" Count="0" />
      <LineId Id="46" Count="0" />
      <LineId Id="66" Count="0" />
      <LineId Id="50" Count="0" />
      <LineId Id="52" Count="0" />
      <LineId Id="54" Count="0" />
      <LineId Id="56" Count="2" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>