<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="Pedal" Id="{b480e77f-b772-4b6b-8c1b-2f16ad405884}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Pedal
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[	]]></ST>
    </Implementation>
    <LineIds Name="Pedal">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>